
import { Shield } from 'lucide-react';

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="section bg-black/30 backdrop-blur-sm">
      <div className="flex justify-center mb-6">
        <Shield className="w-12 h-12 text-cyberpunk-blue" />
      </div>
      
      <h2 className="section-heading">
        Legal <span className="gold-gradient-text">Disclaimer</span>
      </h2>
      
      <div className="glass-card p-8 max-w-4xl mx-auto">
        <h3 className="text-xl font-semibold mb-4 text-white">Information Purpose</h3>
        <p className="text-white/80 mb-6">
          The "Uncovering Hidden Historical Patterns GPT" is provided for educational and informational purposes only. 
          The content generated by this tool does not constitute professional advice, and users should not rely solely on 
          this information without conducting their own research and verification.
        </p>
        
        <h3 className="text-xl font-semibold mb-4 text-white">No Guarantees</h3>
        <p className="text-white/80 mb-6">
          While we strive to provide accurate information, we make no representations or warranties of any kind, express or 
          implied, about the completeness, accuracy, reliability, suitability, or availability of the information, content, 
          or related graphics provided by this tool.
        </p>
        
        <h3 className="text-xl font-semibold mb-4 text-white">Critical Thinking Required</h3>
        <p className="text-white/80 mb-6">
          Users are encouraged to exercise critical thinking and to cross-reference information from multiple sources. 
          The tool is designed to present alternative perspectives and to identify patterns, not to provide definitive 
          historical truths.
        </p>
        
        <h3 className="text-xl font-semibold mb-4 text-white">Not an Endorsement</h3>
        <p className="text-white/80 mb-6">
          The inclusion of any information or analysis does not constitute an endorsement of particular viewpoints, 
          political positions, or interpretations of historical events. This tool aims to present multiple perspectives 
          for educational purposes.
        </p>
        
        <h3 className="text-xl font-semibold mb-4 text-white">Limitation of Liability</h3>
        <p className="text-white/80">
          In no event will AI WEB TOOLS LLC, its affiliates, or service providers be liable for any loss or damage including without 
          limitation, indirect or consequential loss or damage, arising out of, or in connection with, the use of this tool. 
          By using "Uncovering Hidden Historical Patterns GPT," you acknowledge and agree to these terms.
        </p>
      </div>
    </section>
  );
};

export default DisclaimerSection;
